package dotty.tools
package backend
package jvm

import scala.tools.asm.util.{Textifier, TraceClassVisitor, TraceMethodVisitor}
import scala.tools.asm.ClassReader
import scala.tools.asm.tree.*
import java.io.PrintWriter

object TraceUtils {

  /**
   * Print the bytecode of methods generated by GenBCode to the standard output. Only methods
   * whose name contains `traceMethodPattern` are traced.
   */
  private val traceMethodEnabled = sys.env.contains("printBCODE")
  private val traceMethodPattern = sys.env.getOrElse("printBCODE", "")

  /**
   * Print the bytecode of classes generated by GenBCode to the standard output.
   */
  private val traceClassEnabled = false
  private val traceClassPattern = ""

  /**
   * Print the bytecode of classes as they are serialized by the ASM library. The serialization
   * performed by `asm.ClassWriter` can change the code generated by GenBCode. For example, it
   * introduces stack map frames, it computes the maximal stack sizes, and it replaces dead
   * code by NOPs (see also https://github.com/scala/scala/pull/3726#issuecomment-42861780).
   */
  private val traceSerializedClassEnabled = false
  private val traceSerializedClassPattern = ""

  def traceMethodIfRequested(mnode: MethodNode): Unit =
    if (traceMethodEnabled && mnode.name.contains(traceMethodPattern))
      traceMethod(mnode)

  def traceClassIfRequested(cnode: ClassNode): Unit =
    if (traceClassEnabled && cnode.name.contains(traceClassPattern))
      traceClass(cnode)

  def traceSerializedClassIfRequested(internalName: String, bytes: Array[Byte]): Unit =
    if TraceUtils.traceSerializedClassEnabled && internalName.contains(TraceUtils.traceSerializedClassPattern) then
      TraceUtils.traceClass(bytes)

  def traceMethod(mnode: MethodNode): Unit = {
    println(s"Bytecode for method ${mnode.name}")
    val p = new Textifier
    val tracer = new TraceMethodVisitor(p)
    mnode.accept(tracer)
    val w = new PrintWriter(System.out)
    p.print(w)
    w.flush()
  }

  def traceClass(cnode: ClassNode): Unit = {
    println(s"Bytecode for class ${cnode.name}")
    val w = new PrintWriter(System.out)
    cnode.accept(new TraceClassVisitor(w))
    w.flush()
  }

  def traceClass(bytes: Array[Byte]): Unit = traceClass(readClass(bytes))

  private def readClass(bytes: Array[Byte]): ClassNode = {
    val node = new ClassNode()
    new ClassReader(bytes).accept(node, 0)
    node
  }
}
