package dotty.tools.dottydoc
package js

import scala.scalajs.js
import js.Dynamic.global
import js.JSApp
import js.annotation.{ JSExport, JSName }
import org.scalajs.dom
import model.Entities._
import html.IndexLayout

@JSExport object DottyDocJS {
  @JSExport def main(target: dom.html.Div) = {
    global.document.title = "Dotty " + Index.currentEntity.path.mkString(".")
    target.appendChild(IndexLayout.layout(Index.currentEntity).render)
    hljs.initHighlightingOnLoad()
  }
}

/** The unpickled AST available as scala classes */
object Index {
  import prickle._
  import model.Entities._

  val packages: Map[String, Package] = Unpickle[Map[String, Package]]
    .fromString(js.JSON.stringify(UnparsedIndex.packages))
    .toOption
    .getOrElse(Map.empty)

  val currentEntity: Entity = Unpickle[Entity]
    .fromString(js.JSON.stringify(UnparsedIndex.currentEntity))
    .toOption
    .getOrElse(NonEntity)
}

/** Unparsed index stores the pickled AST generated by the dottydoc tool */
@js.native object UnparsedIndex extends js.Object {
  def packages: js.Any = js.native

  def currentEntity: js.Any = js.native
}

/** Library wrapper for highlighting */
@js.native object hljs extends js.Object {
  def initHighlightingOnLoad(): js.Any = js.native
}
