package dotty.tools.dottydoc
package js

import scala.scalajs.js
import js.Dynamic.global
import js.JSApp
import js.annotation.JSName

/** The unpickled AST available as scala classes */
object EntityIndex {
  import microjson._
  import prickle._
  import model.Entities._

  lazy val packages: Map[String, Package] =
    //FIXME
    //Unpickle[Map[String, Package]]
    //.fromString(js.JSON.stringify(Unparsed.packages))
    //.from[js.Object](Unparsed.packages)
    //.toOption
    None
    .getOrElse(Map.empty)

  val currentEntity: Entity = Unpickle[Entity]
    .fromString(js.JSON.stringify(Unparsed.currentEntity))
    .toOption
    .get

  /** Unparsed index stores the pickled AST generated by the dottydoc tool */
  @js.native @JSName("UnparsedIndex") private object Unparsed extends js.Object {
    def packages: js.Object = js.native
    def currentEntity: js.Object = js.native
  }
}
