object Test:
  def main(args: Array[String]): Unit =
    assert(Macro.liftPoint == Point(1, 2), Macro.liftPoint)
    assert(Macro.liftPerson == Namespace.Person("nyc", Address("nyc", 10001)), Macro.liftPerson)
    assert(Macro.liftSingleton == Singleton, Macro.liftSingleton)
    assert(Macro.liftBoxInt == Box(1), Macro.liftBoxInt)
    assert(Macro.liftBoxString == Box("s"), Macro.liftBoxString)
    assert(Macro.liftBoxBox == Box(Box(1)), Macro.liftBoxBox)
    assert(Macro.liftMixed == Mixed("m", true, 1.5), Macro.liftMixed)
    assert(Macro.liftTagged == Tagged(List(1, 2, 3)), Macro.liftTagged)
    assert(Macro.liftWithOpt == WithOpt(Some("hi")), Macro.liftWithOpt)
    assert(Macro.liftWithEither == WithEither(Left(5)), Macro.liftWithEither)
    assert(Macro.liftWithMap == WithMap(Map("a" -> 1, "b" -> 2)), Macro.liftWithMap)
    assert(Macro.liftWithSet == WithSet(Set(1L, 2L)), Macro.liftWithSet)
    assert(Macro.showWithArrayTree.contains("Array"), Macro.showWithArrayTree)
    assert(Macro.liftWithTuple == WithTuple((1, List("a", "b"))), Macro.liftWithTuple)
    assert(Macro.showTupleConsTree.contains("2.5"), Macro.showTupleConsTree)
    assert(Macro.liftCircle == Shape.Circle(1.0), Macro.liftCircle)
    assert(Macro.liftShapeCircle == Shape.Circle(2.0), Macro.liftShapeCircle)
    assert(Macro.liftShapeRect == Shape.Rect(1.0, 2.0), Macro.liftShapeRect)
    assert(Macro.liftShapeOrigin == Shape.Origin, Macro.liftShapeOrigin)
    assert(Macro.liftColorRed == Color.Red, Macro.liftColorRed)
    assert(Macro.liftColorGreen == Color.Green, Macro.liftColorGreen)
    assert(Macro.liftColorCustom == Color.Custom("#fff"), Macro.liftColorCustom)
    assert(Macro.liftMarker == Marker, Macro.liftMarker)
    assert(Macro.liftContainer == Container("c", Shape.Circle(3.0)), Macro.liftContainer)
    assert(Macro.liftBlank == Blank(), Macro.liftBlank)
    assert(Macro.liftResultOk == Result.Ok(5), Macro.liftResultOk)
    assert(Macro.liftResultFail == Result.Fail, Macro.liftResultFail)
    assert(Macro.showPointTree.contains("fromProduct"), Macro.showPointTree)
