#!/usr/bin/env bash

set -e

source $(dirname $0)/cmdTestsCommon.inc.sh

# check that benchmarks can run
"$SBT" "scala3-bench/jmh:run -wi 1 -i 1 -- tests/pos/alias.scala"
# The above is here as it relies on the bootstrapped library.
"$SBT" "scala3-bench-bootstrapped/jmh:run -wi 1 -i 1 -- tests/pos/alias.scala"
"$SBT" "scala3-bench-bootstrapped/jmh:run -wi 1 -i 1 -- -with-compiler compiler/src/dotty/tools/dotc/core/Types.scala"

echo "testing scala.quoted.Expr.run from sbt scala"
"$SBT" ";scala3-compiler-bootstrapped/scalac -with-compiler tests/run-staging/quote-run.scala; scala3-compiler-bootstrapped/scala -with-compiler Test" > "$tmp"
grep -qe "val a: scala.Int = 3" "$tmp"


# setup for `scalac`/`scala` script tests
"$SBT" dist/pack

# check that `scalac` compiles and `scala` runs it
echo "testing ./bin/scalac and ./bin/scala"
clear_out "$OUT"
./bin/scalac "$SOURCE" -d "$OUT"
./bin/scala -classpath "$OUT" "$MAIN" > "$tmp"
test "$EXPECTED_OUTPUT" = "$(cat "$tmp")"

# Test scaladoc based on compiled classes
./bin/scaladoc -project Staging -d "$OUT1" "$OUT"
clear_out "$OUT1"

# check that `scalac` and `scala` works for staging
clear_out "$OUT"
./bin/scalac tests/run-staging/i4044f.scala -d "$OUT"
./bin/scala -with-compiler -classpath "$OUT" Test > "$tmp"

# check that `scalac -from-tasty` compiles and `scala` runs it
echo "testing ./bin/scalac -from-tasty and scala -classpath"
clear_out "$OUT1"
./bin/scalac "$SOURCE" -d "$OUT"
./bin/scalac -from-tasty -d "$OUT1" "$OUT/$TASTY"
./bin/scala -classpath "$OUT1" "$MAIN" > "$tmp"
test "$EXPECTED_OUTPUT" = "$(cat "$tmp")"

# check that `sbt scalac -decompile` runs
echo "testing sbt scalac -decompile from file"
./bin/scalac -decompile -color:never "$OUT/$TASTY" > "$tmp"
grep -qe "def main(args: scala.Array\[scala.Predef.String\]): scala.Unit =" "$tmp"

echo "testing loading tasty from .tasty file in jar"
clear_out "$OUT"
./bin/scalac -d "$OUT/out.jar" "$SOURCE"
./bin/scalac -decompile -color:never "$OUT/out.jar" > "$tmp"
grep -qe "def main(args: scala.Array\[scala.Predef.String\]): scala.Unit =" "$tmp"

# echo ":quit" | ./dist/target/pack/bin/scala  # not supported by CI

echo "testing ./bin/scaladoc"
clear_out "$OUT1"
./bin/scaladoc -project Hello -d "$OUT1" "$OUT/out.jar"

# check compilation when the class/tasty files already exist in the current directory
echo "testing i11644"
cwd=$(pwd)
clear_out "$OUT"
(cd "$OUT" && "$cwd/bin/scalac" "$cwd/tests/pos/i11644.scala" && "$cwd/bin/scalac" "$cwd/tests/pos/i11644.scala")

# check options specified in files
./bin/scalac @project/scripts/options "$SOURCE"

# test command line options
./bin/scalac -help > "$tmp" 2>&1
grep -qe "Usage: scalac <options> <source files>" "$tmp"

./bin/scala -help > "$tmp" 2>&1
grep -qe "Usage: scala <options> <source files>" "$tmp"

./bin/scala -d hello.jar tests/run/hello.scala
ls hello.jar

echo "testing i12973"
clear_out "$OUT"
./bin/scalac -d "$OUT/out.jar" tests/pos/i12973.scala
echo "Bug12973().check" | TERM=dumb ./bin/scala -cp "$OUT/out.jar" > "$tmp" 2>&1
grep -qe "Bug12973 is fixed" "$tmp"

echo "testing -sourcepath with inlining"
cwd=$(pwd)
java_prop="-Dpack.version.file=$cwd/dist/target/pack/VERSION"
sbt_test_command=";clean;prepareSources;compile;copyChanges;compile"
(cd "$cwd/tests/cmdTest-sbt-tests/sourcepath-with-inline" && "$SBT" "$java_prop" "$sbt_test_command")
rm -rf "$cwd/tests/cmdTest-sbt-tests/sourcepath-with-inline/target"
rm -rf "$cwd/tests/cmdTest-sbt-tests/sourcepath-with-inline/project/target"
rm -f "$cwd/tests/cmdTest-sbt-tests/sourcepath-with-inline/src/main/scala/a/zz.scala"
