#!/usr/bin/env bash

set -e

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >& /dev/null && pwd)/../.."
SBT="$ROOT/project/scripts/sbt" # if run on CI

# set the $DIST_PROJECT and $DIST_DIR variables
source "$ROOT/bin/common-platform"

# build the scala/scalac/scaladoc binary, where scala is native for the current platform.
"$SBT" "$DIST_PROJECT/pack"
