#!/usr/bin/env sh
set -eux

# if build is PR rebase on top of target branch
if [ "$DRONE_BUILD_EVENT" = "pull_request" ]; then
  git config user.email "allan.renucci@gmail.com"
  git config user.name "Allan Renucci"
  git pull --rebase "$DRONE_REMOTE_URL" "$DRONE_BRANCH"
fi

# clone submodules in parallel
git submodule update --init --recursive --jobs 3
