#!/usr/bin/env bash

source $(dirname $0)/cmdTestsCommon.inc.sh

echo "testing scaladoc script"
clear_out "$OUT"
clear_out "$OUT1"


STDLIB_COMMAND="$SBT \"eval println(Build.stdlibVersion(Modes.NonBootstrapped))\""
STDLIB_VERSION=$(eval $STDLIB_COMMAND | tail -n 2 | head -n 1)

DOTTY_NONBOOTSTRAPPED_VERSION_COMMAND="$SBT \"eval println(Build.dottyNonBootstrappedVersion)\""
DOTTY_NONBOOTSTRAPPED_VERSION=$(eval $DOTTY_NONBOOTSTRAPPED_VERSION_COMMAND | tail -n 2 | head -n 1)

DOTTY_BOOTSTRAPPED_VERSION_COMMAND="$SBT \"eval println(Build.dottyVersion)\""
DOTTY_BOOTSTRAPPED_VERSION=$(eval $DOTTY_BOOTSTRAPPED_VERSION_COMMAND | tail -n 2 | head -n 1)

GITHUB_REPOSITORY="lampepfl/dotty"
GITHUB_SHA="3.0.0"

"$SBT" "scaladoc/generateTestcasesDocumentation" > "$tmp" 2>&1 || echo "generated testcases project with sbt"
dist/target/pack/bin/scaladoc \
  -d "$OUT1" \
  -project "scaladoc testcases" \
  -source-links:out/bootstrap/stdlib-bootstrapped/scala-"${DOTTY_NONBOOTSTRAPPED_VERSION}"/src_managed/main/scala-library-src=github://scala/scala/v"${STDLIB_VERSION}"#src/library \
  -source-links:out/bootstrap/stdlib-bootstrapped/scala-"${DOTTY_NONBOOTSTRAPPED_VERSION}"/src_managed/main/dotty-library-src=github://"${GITHUB_REPOSITORY}"/"${GITHUB_SHA}"\#library/src \
  -source-links:github://"${GITHUB_REPOSITORY}"/"${GITHUB_SHA}" \
  "-external-mappings:.*scala/.*::scaladoc3::https://dotty.epfl.ch/api/,.*java/.*::javadoc::https://docs.oracle.com/javase/8/docs/api/" \
  "-skip-by-regex:.+\.internal($|\..+)" \
  "-skip-by-regex:.+\.impl($|\..+)" \
  -project-logo docs/_assets/images/logo.svg \
  -social-links:github::https://github.com/lampepfl/dotty,discord::https://discord.com/invite/scala,twitter::https://twitter.com/scala_lang \
  -Ygenerate-inkuire \
  "-skip-by-id:scala.runtime.stdLibPatches" \
  "-skip-by-id:scala.runtime.MatchCase" \
  "-snippet-compiler:scaladoc-testcases/docs=compile" \
  "-comment-syntax:scaladoc-testcases/src/example/comment-md=markdown,scaladoc-testcases/src/example/comment-wiki=wiki" \
  -siteroot scaladoc-testcases/docs \
  -project-footer "Copyright (c) 2002-2022, LAMP/EPFL" \
  -default-template static-site-main \
  -author -groups -revision main -project-version "${DOTTY_BOOTSTRAPPED_VERSION}" \
  "-quick-links:Download::https://www.scala-lang.org/download/,Documentation::https://docs.scala-lang.org/,Libraries::https://index.scala-lang.org,Contribute::https://www.scala-lang.org/contribute/,Blog::https://www.scala-lang.org/blog/,Community::https://www.scala-lang.org/community/" \
  out/bootstrap/scaladoc-testcases/scala-"${DOTTY_NONBOOTSTRAPPED_VERSION}"/classes > "$tmp" 2>&1 || echo "generated testcases project with scripts"
diff -rq "$OUT1" "scaladoc/output/testcases"
