#!/usr/bin/env bash

# Usage:
# ./sbt <cmd>

CMD="$1"

if [ -z "$CMD" ]; then
  echo "Error: missing sbt command"
  exit 1
fi

# run sbt with the supplied arg
sbt -J-Xmx4096m \
    -J-XX:ReservedCodeCacheSize=512m \
    -J-XX:MaxMetaspaceSize=1024m \
    -Ddotty.drone.mem=4096m \
    -ivy /var/cache/drone/ivy2 \
    "$CMD"
