#!/usr/bin/env bash

# Usage:
# SONATYPE_USER=<sonatype user> SONATYPE_PW=<sonatype pw> PGP_PW=<pgp pw> ./sbtPublish <publish cmd>

set -e

# Release command:
RELEASE_CMD="$1"

if [ -z "$SONATYPE_USER" ] || [ -z "$SONATYPE_PW" ] || [ -z "$PGP_PW" ]; then
    echo "Error: SONATYPE_USER, SONATYPE_PW or PGP_PW env unset"
    exit 1
fi

if [ ! "$NIGHTLYBUILD" = "yes" ] && [ ! "$RELEASEBUILD" = "yes" ]; then
    echo "Neither NIGHTLYBUILD nor RELEASEBUILD env var set to \"yes\""
    exit 1
fi

if [ -z "$RELEASE_CMD" ]; then
  echo "Error: missing publish command"
  exit 1
fi

CMD="     ;set credentials in ThisBuild := Seq(Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$2\", \"$3\"))"
CMD="$CMD ;set pgpPassphrase := Some(\"\"\"$4\"\"\".toCharArray)"
CMD="$CMD ;set pgpSecretRing := file(\"/keys/secring.asc\")"
CMD="$CMD ;set pgpPublicRing := file(\"/keys/pubring.asc\")"
CMD="$CMD $RELEASE_CMD"

# run sbt with the supplied arg
SBT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >& /dev/null && pwd)/sbt"
eval "$SBT" "$CMD"
