#!/usr/bin/env bash

# Release command:
RELEASE_CMD="$1"

if [ -z "$SONATYPE_USER" ] || [ -z "$SONATYPE_PW" ] || [ -z "$PGP_PW" ]; then
    echo "Error: SONATYPE_USER, SONATYPE_PW or PGP_PW env unset"
    exit 1
fi

if [ ! "$NIGHTLYBUILD" = "yes" ] && [ ! "$RELEASEBUILD" = "yes" ]; then
    echo "Neither NIGHTLYBUILD nor RELEASEBUILD env var set to \"yes\""
    exit 1
fi

if [ -z "$RELEASE_CMD" ]; then
  echo "Error: missing publish command"
  exit 1
fi

CMD="     ;set credentials in ThisBuild := Seq(Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$2\", \"$3\"))"
CMD="$CMD ;set pgpPassphrase := Some(\"\"\"$4\"\"\".toCharArray)"
CMD="$CMD ;set pgpSecretRing := file(\"/keys/secring.asc\")"
CMD="$CMD ;set pgpPublicRing := file(\"/keys/pubring.asc\")"
CMD="$CMD $RELEASE_CMD"

sbt -J-Xmx4096m \
    -J-XX:ReservedCodeCacheSize=512m \
    -J-XX:MaxMetaspaceSize=1024m \
    -Ddotty.drone.mem=4096m \
    "$CMD"
