#!/usr/bin/env bash

update() {
  [[ -d $baseDir ]] || mkdir -p $baseDir
  cd $baseDir

  if [ ! -d $baseDir/$3 ]; then git clone "https://github.com/$1/$2.git" $3; fi

  cd $3

  git fetch --tags "https://github.com/$1/$2.git"
  (git fetch "https://github.com/$1/$2.git" $4 && git checkout -fq FETCH_HEAD) #|| git checkout -fq $4 # || fallback is for local testing on tag
  git reset --hard
  echo updated $1/$2:$4 under $3. Last commits:
  git --no-pager log --pretty=format:"%h - %an, %aD : %s" -n 10 # show last commits
  cd -
}

export LC_ALL=en_US.UTF-8

baseDir=`pwd`

update DarkDimius scala scala-scala dotty-library
