package example

class MethodUsages/*<-example::MethodUsages#*/ {
  val m/*<-example::MethodUsages#m.*/ = new Methods/*->example::Methods#*/[Int/*->scala::Int#*/]
  m/*->example::MethodUsages#m.*/.m1/*->example::Methods#m1().*/
  m/*->example::MethodUsages#m.*/.m2/*->example::Methods#m2().*/()
  m/*->example::MethodUsages#m.*/.m3/*->example::Methods#m3().*/(0)
  m/*->example::MethodUsages#m.*/.m4/*->example::Methods#m4().*/(0)(0)
  m/*->example::MethodUsages#m.*/.m5/*->example::Methods#m5().*/("")
  m/*->example::MethodUsages#m.*/.m5/*->example::Methods#m5(+1).*/(0)
  m/*->example::MethodUsages#m.*/.m6/*->example::Methods#m6().*/(0)
  m/*->example::MethodUsages#m.*/.m6/*->example::Methods#m6(+1).*/(new m/*->example::MethodUsages#m.*/.List/*->example::Methods#List#*/[Int/*->scala::Int#*/])
  m/*->example::MethodUsages#m.*/.m6/*->example::Methods#m6(+2).*/(Nil/*->scala::package.Nil.*/)
  m/*->example::MethodUsages#m.*/.m7/*->example::Methods#m7().*/(m/*->example::MethodUsages#m.*/, new m/*->example::MethodUsages#m.*/.List/*->example::Methods#List#*/[Int/*->scala::Int#*/])
  m/*->example::MethodUsages#m.*/.`m8().`/*->example::Methods#`m8().`().*/()
  m/*->example::MethodUsages#m.*/.m9/*->example::Methods#m9().*/(null)
  m/*->example::MethodUsages#m.*/.m10/*->example::Methods#m10().*/(null)
  m/*->example::MethodUsages#m.*/.m11/*->example::Methods#m11().*/(Predef/*->scala::Predef.*/)
  m/*->example::MethodUsages#m.*/.m11/*->example::Methods#m11(+1).*/(Example/*->example::Example.*/)
  m/*->example::MethodUsages#m.*/.m12a/*->example::Methods#m12a().*/(null)
  m/*->example::MethodUsages#m.*/.m12b/*->example::Methods#m12b().*/(null)
  m/*->example::MethodUsages#m.*/.m13/*->example::Methods#m13().*/(0)
  m/*->example::MethodUsages#m.*/.m15/*->example::Methods#m15().*/(0)
  m/*->example::MethodUsages#m.*/.m16/*->example::Methods#m16().*/(0)
  m/*->example::MethodUsages#m.*/.m16/*->example::Methods#m16().*/(0)
  m/*->example::MethodUsages#m.*/.m17/*->example::Methods#m17.*/.m/*->example::Methods#m17.m().*/()
  m/*->example::MethodUsages#m.*/.m17/*->example::Methods#m17().*/(1)
  m/*->example::MethodUsages#m.*/.m17/*->example::Methods#m17(+1).*/("")
  m/*->example::MethodUsages#m.*/.m18/*->example::Methods#m18.*/.m/*->example::Methods#m17.m().*/()
  m/*->example::MethodUsages#m.*/.m18/*->example::Methods#m18().*/(1)
  m/*->example::MethodUsages#m.*/.m18/*->example::Methods#m18(+1).*/("")
  m/*->example::MethodUsages#m.*/.m19/*->example::Methods#m19().*/(1,2)(3)
  m/*->example::MethodUsages#m.*/.m20/*->example::Methods#m20().*/(1)
  m/*->example::MethodUsages#m.*/.m20/*->example::Methods#m20(+1).*/("")
  m/*->example::MethodUsages#m.*/.m20/*->example::Methods#m20(+2).*/.m/*->example::Methods#m17.m().*/()
}
