package dotty.tools.dotc
package transform

import core.*
import Flags.*
import Contexts.*
import Symbols.*
import DenotTransformers.SymTransformer
import Types.MethodType
import Annotations.Annotation
import SymDenotations.SymDenotation
import Names.Name
import StdNames.nme
import NameOps.*
import LazyVals.{isVarHandleForLazy, isMethodLookupForLazy}

import ast.*

import scala.collection.mutable

import MegaPhase.*

/** Move static methods from companion to the class itself. Also create the static constructor.
 *  VarHandles generated by the compiler (more in LazyVals.scala) are left in the original class.
 *  MethodSymbols.lookup() generated by the compiler is extracted to be a local static constructor value.
 */
class MoveStatics extends MiniPhase with SymTransformer {
  import ast.tpd.*

  override def phaseName: String = MoveStatics.name

  override def description: String = MoveStatics.description

  def transformSym(sym: SymDenotation)(using Context): SymDenotation =
    if (sym.hasAnnotation(defn.ScalaStaticAnnot) && sym.owner.is(Flags.Module) && sym.owner.companionClass.exists &&
        (sym.is(Flags.Method) || !(sym.isMutableVarOrAccessor && sym.owner.companionClass.is(Flags.Trait)) &&
        !sym.symbol.isVarHandleForLazy && !sym.symbol.isMethodLookupForLazy)) {
      sym.owner.asClass.delete(sym.symbol)
      sym.owner.companionClass.asClass.enter(sym.symbol)
      sym.copySymDenotation(owner = sym.owner.companionClass)
    }
    else sym

  override def transformStats(trees: List[Tree])(using Context): List[Tree] =
    if (ctx.owner.is(Flags.Package)) {
      val (classes, others) = trees.partition(x => x.isInstanceOf[TypeDef] && x.symbol.isClass)
      val pairs = classes.groupBy(_.symbol.name.stripModuleClassSuffix).asInstanceOf[Map[Name, List[TypeDef]]]

      /** Rebuilds a template with static ValDefs from `newBody`` initialized in a static constructor.
       *  `localStaticDefs`, used for initialisation of other static values,
       *   are moved entirely into the static constructor.
       */
      def rebuild(orig: TypeDef, newBody: List[Tree], localStaticDefs: List[ValDef]): Tree = {
        val staticFields = newBody.filter(x => x.isInstanceOf[ValDef] && x.symbol.hasAnnotation(defn.ScalaStaticAnnot)).asInstanceOf[List[ValDef]]
        val newBodyWithStaticConstr =
          if (staticFields.nonEmpty) {
            /* do NOT put Flags.JavaStatic here. It breaks .enclosingClass */
            val staticCostructor = newSymbol(orig.symbol, nme.STATIC_CONSTRUCTOR, Flags.Synthetic | Flags.Method | Flags.Private, MethodType(Nil, defn.UnitType))
            staticCostructor.addAnnotation(Annotation(defn.ScalaStaticAnnot, staticCostructor.span))
            staticCostructor.entered

            val symbolRemap = localStaticDefs.map { x =>
              x.symbol.owner.asClass.delete(x.symbol)
              x.changeOwner(x.symbol.owner, staticCostructor)
              (x.symbol, x.symbol.copy(owner = staticCostructor))
            }.toMap

            val localValDefs = localStaticDefs.map ( vDef =>
              val newSymbol = symbolRemap(vDef.symbol)
              ValDef(newSymbol.asTerm, vDef.rhs.changeOwner(vDef.symbol, newSymbol))
            )

            val localValDefMapper = new TreeMap:
              override def transform(tree: Tree)(using Context): Tree = tree match
                case ident @ Ident(tp) if symbolRemap.contains(ident.symbol) => ref(symbolRemap(ident.symbol))
                case _ => super.transform(tree)

            val staticAssigns = staticFields.map(x => Assign(ref(x.symbol), localValDefMapper.transform(x.rhs).changeOwner(x.symbol, staticCostructor)))
            tpd.DefDef(staticCostructor, Block(localValDefs ++ staticAssigns, tpd.unitLiteral)) :: newBody
          }
          else newBody

        val oldTemplate = orig.rhs.asInstanceOf[Template]
        cpy.TypeDef(orig)(rhs = cpy.Template(oldTemplate)(body = newBodyWithStaticConstr))
      }

      def move(module: TypeDef, companion: TypeDef): List[Tree] = {
        assert(companion != module)
        if (!module.symbol.is(Flags.Module)) move(companion, module)
        else {
          val moduleTmpl = module.rhs.asInstanceOf[Template]
          val companionTmpl = companion.rhs.asInstanceOf[Template]

          val staticDefs = mutable.ListBuffer[Tree]()
          val staticTiedDefs = mutable.ListBuffer[Tree]()
          val localStaticDefs = mutable.ListBuffer[ValDef]()
          val remainingDefs = mutable.ListBuffer[Tree]()

          moduleTmpl.body.foreach {
            case valDef: ValDef if valDef.symbol.isMethodLookupForLazy && valDef.symbol.isScalaStatic =>
              localStaticDefs.addOne(valDef)
            case memberDef: MemberDef if memberDef.symbol.isScalaStatic =>
              if memberDef.symbol.isVarHandleForLazy then
                staticTiedDefs.addOne(memberDef)
              else
                staticDefs.addOne(memberDef)
            case other => remainingDefs.addOne(other)
          }

          rebuild(companion, companionTmpl.body ++ staticDefs, Nil) :: rebuild(module, staticTiedDefs.toList ++ remainingDefs.toList, localStaticDefs.toList) :: Nil
        }
      }
      val newPairs =
        for ((name, classes) <- pairs)
          yield
            if (classes.tail.isEmpty) {
              val classDef = classes.head
              val tmpl = classDef.rhs.asInstanceOf[Template]
              val (localStaticDefs, remainingDefs) = tmpl.body.partition {
                case valDef: ValDef => valDef.symbol.isMethodLookupForLazy && valDef.symbol.isScalaStatic
                case _ => false
              }
              rebuild(classDef, remainingDefs, localStaticDefs.asInstanceOf[List[ValDef]]) :: Nil
            }
            else move(classes.head, classes.tail.head)
      Trees.flatten(newPairs.toList.flatten ++ others)
    }
    else trees
}

object MoveStatics {
  val name: String = "moveStatic"
  val description: String = "move static methods from companion to the class itself"
}
