class hello.Hello extends java.lang.this#Object with scala.this#Matchable with scala.this#Any {
^inherited^ def java;lang;Object;init;(): java.lang.this#Object
^inherited^ final def eq(x$0: java.lang.this#Object): scala.this#Boolean
^inherited^ final def ne(x$0: java.lang.this#Object): scala.this#Boolean
^inherited^ final def synchronized[ X0 >: scala.this#Nothing <: scala.this#Any](x$0: <X0>): <X0>
^inherited^ protected def clone(): java.lang.this#Object
^inherited^ protected def finalize(): scala.this#Unit
^inherited^ final def notify(): scala.this#Unit
^inherited^ final def notifyAll(): scala.this#Unit
^inherited^ final def wait(): scala.this#Unit
^inherited^ final def wait(x$0: scala.this#Long): scala.this#Unit
^inherited^ final def wait(x$0: scala.this#Long, x$1: scala.this#Int): scala.this#Unit
^inherited^ override def equals(x$0: scala.this#Any): scala.this#Boolean
^inherited^ override def hashCode(): scala.this#Int
^inherited^ final def ==(x$0: scala.this#Any): scala.this#Boolean
^inherited^ final def !=(x$0: scala.this#Any): scala.this#Boolean
^inherited^ def equals(x$0: scala.this#Any): scala.this#Boolean
^inherited^ def hashCode(): scala.this#Int
^inherited^ def toString(): java.lang.this#String
^inherited^ final def ##: scala.this#Int
^inherited^ final def getClass[ X0 >: scala.Any.this <: scala.this#Any](): java.lang.this#Class[<_> forSome { type  _ >: scala.this#Nothing <: <X0> }]
^inherited^ final def isInstanceOf[ X0 >: scala.this#Nothing <: scala.this#Any]: scala.this#Boolean
^inherited^ final def asInstanceOf[ X0 >: scala.this#Nothing <: scala.this#Any]: <X0>
^inherited^ final def $isInstanceOf[ X0 >: scala.this#Nothing <: scala.this#Any]: scala.this#Boolean
^inherited^ final def $asInstanceOf[ X0 >: scala.this#Nothing <: scala.this#Any]: <X0>

def hello;Hello;init;(): hello.this#Hello
}
Used Names:
===========
class Hello: hello in [Default], Unit in [Default], java$u003Blang$u003BObject$u003Binit$u003B in [Default], Object in [Default], 

Dependencies:
=============
class Hello: class Object in [DependencyByMemberRefDependencyByInheritance], class Unit in [DependencyByMemberRef], 
