package scala.quoted.compiletime.internal

import scala.quoted.{Expr, Type}
import scala.quoted.compiletime as pub
import scala.quoted.runtime.impl.{ExprImpl, TypeImpl}

/////// General ///////////////////////////////////////////////////////////////

extension (self: Expr[?]) private[internal] inline def cast: ExprImpl = self.asInstanceOf[ExprImpl]
extension (self: Type[?]) private[internal] inline def cast: TypeImpl = self.asInstanceOf[TypeImpl]

extension (self: pub.Flags) private[internal] inline def cast: Flags = self.asInstanceOf[Flags]
extension (self: pub.Position) private[internal] inline def cast: Position = self.asInstanceOf[Position]
extension (self: pub.SourceFile) private[internal] inline def cast: SourceFile = self.asInstanceOf[SourceFile]
extension (self: pub.Symbol) private[internal] inline def cast: Symbol = self.asInstanceOf[Symbol]
extension (self: pub.Signature) private[internal] inline def cast: Signature = self.asInstanceOf[Signature]

/////// Constant ///////////////////////////////////////////////////////////////

extension (self: pub.Constant) private[internal] inline def cast: pub.Constant & Constant = self.asInstanceOf[pub.Constant & Constant]
extension (self: pub.BooleanConstant) private[internal] inline def cast: BooleanConstant = self.asInstanceOf[BooleanConstant]
extension (self: pub.ByteConstant) private[internal] inline def cast: ByteConstant = self.asInstanceOf[ByteConstant]
extension (self: pub.ShortConstant) private[internal] inline def cast: ShortConstant = self.asInstanceOf[ShortConstant]
extension (self: pub.IntConstant) private[internal] inline def cast: IntConstant = self.asInstanceOf[IntConstant]
extension (self: pub.LongConstant) private[internal] inline def cast: LongConstant = self.asInstanceOf[LongConstant]
extension (self: pub.FloatConstant) private[internal] inline def cast: FloatConstant = self.asInstanceOf[FloatConstant]
extension (self: pub.DoubleConstant) private[internal] inline def cast: DoubleConstant = self.asInstanceOf[DoubleConstant]
extension (self: pub.CharConstant) private[internal] inline def cast: CharConstant = self.asInstanceOf[CharConstant]
extension (self: pub.StringConstant) private[internal] inline def cast: StringConstant = self.asInstanceOf[StringConstant]
extension (self: pub.UnitConstant) private[internal] inline def cast: UnitConstant = self.asInstanceOf[UnitConstant]
extension (self: pub.NullConstant) private[internal] inline def cast: NullConstant = self.asInstanceOf[NullConstant]
extension (self: pub.ClassOfConstant) private[internal] inline def cast: ClassOfConstant = self.asInstanceOf[ClassOfConstant]

/////// Selector ///////////////////////////////////////////////////////////////

extension (self: pub.Selector) private[internal] inline def cast: Selector = self.asInstanceOf[Selector]
extension (self: pub.SimpleSelector) private[internal] inline def cast: SimpleSelector = self.asInstanceOf[SimpleSelector]
extension (self: pub.RenameSelector) private[internal] inline def cast: RenameSelector = self.asInstanceOf[RenameSelector]
extension (self: pub.OmitSelector) private[internal] inline def cast: OmitSelector = self.asInstanceOf[OmitSelector]
extension (self: pub.GivenSelector) private[internal] inline def cast: GivenSelector = self.asInstanceOf[GivenSelector]

/////// ParamClause ///////////////////////////////////////////////////////////////

extension (self: pub.ParamClause) private[internal] inline def cast: ParamClause = self.asInstanceOf[ParamClause]
extension (self: pub.TermParamClause) private[internal] inline def cast: TermParamClause = self.asInstanceOf[TermParamClause]
extension (self: pub.TypeParamClause) private[internal] inline def cast: TypeParamClause = self.asInstanceOf[TypeParamClause]

/////// TypeRepr ///////////////////////////////////////////////////////////////

extension (self: pub.TypeRepr) private[internal] inline def cast: TypeRepr = self.asInstanceOf[TypeRepr]
extension (self: pub.NamedType) private[internal] inline def cast: NamedType = self.asInstanceOf[NamedType]
extension (self: pub.TermRef) private[internal] inline def cast: TermRef = self.asInstanceOf[TermRef]
extension (self: pub.TypeRef) private[internal] inline def cast: TypeRef = self.asInstanceOf[TypeRef]
extension (self: pub.ConstantType) private[internal] inline def cast: ConstantType = self.asInstanceOf[ConstantType]
extension (self: pub.SuperType) private[internal] inline def cast: SuperType = self.asInstanceOf[SuperType]
extension (self: pub.Refinement) private[internal] inline def cast: Refinement = self.asInstanceOf[Refinement]
extension (self: pub.AppliedType) private[internal] inline def cast: AppliedType = self.asInstanceOf[AppliedType]
extension (self: pub.AnnotatedType) private[internal] inline def cast: AnnotatedType = self.asInstanceOf[AnnotatedType]
extension (self: pub.AndOrType) private[internal] inline def cast: AndOrType = self.asInstanceOf[AndOrType]
extension (self: pub.AndType) private[internal] inline def cast: AndType = self.asInstanceOf[AndType]
extension (self: pub.OrType) private[internal] inline def cast: OrType = self.asInstanceOf[OrType]
extension (self: pub.MatchType) private[internal] inline def cast: MatchType = self.asInstanceOf[MatchType]
extension (self: pub.ByNameType) private[internal] inline def cast: ByNameType = self.asInstanceOf[ByNameType]
extension (self: pub.ParamRef) private[internal] inline def cast: ParamRef = self.asInstanceOf[ParamRef]
extension (self: pub.ThisType) private[internal] inline def cast: ThisType = self.asInstanceOf[ThisType]
extension (self: pub.RecursiveThis) private[internal] inline def cast: RecursiveThis = self.asInstanceOf[RecursiveThis]
extension (self: pub.RecursiveType) private[internal] inline def cast: RecursiveType = self.asInstanceOf[RecursiveType]
extension (self: pub.LambdaType) private[internal] inline def cast: LambdaType = self.asInstanceOf[LambdaType]
extension (self: pub.MethodOrPoly) private[internal] inline def cast: MethodOrPoly = self.asInstanceOf[MethodOrPoly]
extension (self: pub.MethodType) private[internal] inline def cast: MethodType = self.asInstanceOf[MethodType]
extension (self: pub.PolyType) private[internal] inline def cast: PolyType = self.asInstanceOf[PolyType]
extension (self: pub.TypeLambda) private[internal] inline def cast: TypeLambda = self.asInstanceOf[TypeLambda]
extension (self: pub.MatchCase) private[internal] inline def cast: MatchCase = self.asInstanceOf[MatchCase]
extension (self: pub.TypeBounds) private[internal] inline def cast: TypeBounds = self.asInstanceOf[TypeBounds]
extension (self: pub.NoPrefix) private[internal] inline def cast: NoPrefix = self.asInstanceOf[NoPrefix]
extension (self: pub.FlexibleType) private[internal] inline def cast: FlexibleType = self.asInstanceOf[FlexibleType]

/////// Tree ///////////////////////////////////////////////////////////////

extension (self: pub.Tree) private[internal] inline def cast: Tree = self.asInstanceOf[Tree]
extension (self: pub.PackageClause) private[internal] inline def cast: PackageClause = self.asInstanceOf[PackageClause]
extension (self: pub.Statement) private[internal] inline def cast: Statement = self.asInstanceOf[Statement]
extension (self: pub.Import) private[internal] inline def cast: Import = self.asInstanceOf[Import]
extension (self: pub.Export) private[internal] inline def cast: Export = self.asInstanceOf[Export]
extension (self: pub.Definition) private[internal] inline def cast: Definition = self.asInstanceOf[Definition]
extension (self: pub.ClassDef) private[internal] inline def cast: ClassDef = self.asInstanceOf[ClassDef]
extension (self: pub.ValOrDefDef) private[internal] inline def cast: ValOrDefDef = self.asInstanceOf[ValOrDefDef]
extension (self: pub.DefDef) private[internal] inline def cast: DefDef = self.asInstanceOf[DefDef]
extension (self: pub.ValDef) private[internal] inline def cast: ValDef = self.asInstanceOf[ValDef]
extension (self: pub.TypeDef) private[internal] inline def cast: TypeDef = self.asInstanceOf[TypeDef]
extension (self: pub.Term) private[internal] inline def cast: Term = self.asInstanceOf[Term]
extension (self: pub.Ref) private[internal] inline def cast: Ref = self.asInstanceOf[Ref]
extension (self: pub.Ident) private[internal] inline def cast: Ident = self.asInstanceOf[Ident]
extension (self: pub.Wildcard) private[internal] inline def cast: Wildcard = self.asInstanceOf[Wildcard]
extension (self: pub.Select) private[internal] inline def cast: Select = self.asInstanceOf[Select]
extension (self: pub.Literal) private[internal] inline def cast: Literal = self.asInstanceOf[Literal]
extension (self: pub.This) private[internal] inline def cast: This = self.asInstanceOf[This]
extension (self: pub.New) private[internal] inline def cast: New = self.asInstanceOf[New]
extension (self: pub.NamedArg) private[internal] inline def cast: NamedArg = self.asInstanceOf[NamedArg]
extension (self: pub.Apply) private[internal] inline def cast: Apply = self.asInstanceOf[Apply]
extension (self: pub.TypeApply) private[internal] inline def cast: TypeApply = self.asInstanceOf[TypeApply]
extension (self: pub.Super) private[internal] inline def cast: Super = self.asInstanceOf[Super]
extension (self: pub.Typed) private[internal] inline def cast: Typed = self.asInstanceOf[Typed]
extension (self: pub.Assign) private[internal] inline def cast: Assign = self.asInstanceOf[Assign]
extension (self: pub.Block) private[internal] inline def cast: Block = self.asInstanceOf[Block]
extension (self: pub.Closure) private[internal] inline def cast: Closure = self.asInstanceOf[Closure]
extension (self: pub.If) private[internal] inline def cast: If = self.asInstanceOf[If]
extension (self: pub.Match) private[internal] inline def cast: Match = self.asInstanceOf[Match]
extension (self: pub.SummonFrom) private[internal] inline def cast: SummonFrom = self.asInstanceOf[SummonFrom]
extension (self: pub.Try) private[internal] inline def cast: Try = self.asInstanceOf[Try]
extension (self: pub.Return) private[internal] inline def cast: Return = self.asInstanceOf[Return]
extension (self: pub.Repeated) private[internal] inline def cast: Repeated = self.asInstanceOf[Repeated]
extension (self: pub.Inlined) private[internal] inline def cast: Inlined = self.asInstanceOf[Inlined]
extension (self: pub.SelectOuter) private[internal] inline def cast: SelectOuter = self.asInstanceOf[SelectOuter]
extension (self: pub.While) private[internal] inline def cast: While = self.asInstanceOf[While]
extension (self: pub.TypedOrTest) private[internal] inline def cast: TypedOrTest = self.asInstanceOf[TypedOrTest]
extension (self: pub.TypeTree) private[internal] inline def cast: TypeTree = self.asInstanceOf[TypeTree]
extension (self: pub.Inferred) private[internal] inline def cast: Inferred = self.asInstanceOf[Inferred]
extension (self: pub.TypeIdent) private[internal] inline def cast: TypeIdent = self.asInstanceOf[TypeIdent]
extension (self: pub.TypeSelect) private[internal] inline def cast: TypeSelect = self.asInstanceOf[TypeSelect]
extension (self: pub.TypeProjection) private[internal] inline def cast: TypeProjection = self.asInstanceOf[TypeProjection]
extension (self: pub.Singleton) private[internal] inline def cast: Singleton = self.asInstanceOf[Singleton]
extension (self: pub.Refined) private[internal] inline def cast: Refined = self.asInstanceOf[Refined]
extension (self: pub.Applied) private[internal] inline def cast: Applied = self.asInstanceOf[Applied]
extension (self: pub.Annotated) private[internal] inline def cast: Annotated = self.asInstanceOf[Annotated]
extension (self: pub.MatchTypeTree) private[internal] inline def cast: MatchTypeTree = self.asInstanceOf[MatchTypeTree]
extension (self: pub.ByName) private[internal] inline def cast: ByName = self.asInstanceOf[ByName]
extension (self: pub.LambdaTypeTree) private[internal] inline def cast: LambdaTypeTree = self.asInstanceOf[LambdaTypeTree]
extension (self: pub.TypeBind) private[internal] inline def cast: TypeBind = self.asInstanceOf[TypeBind]
extension (self: pub.TypeBlock) private[internal] inline def cast: TypeBlock = self.asInstanceOf[TypeBlock]
extension (self: pub.TypeBoundsTree) private[internal] inline def cast: TypeBoundsTree = self.asInstanceOf[TypeBoundsTree]
extension (self: pub.WildcardTypeTree) private[internal] inline def cast: WildcardTypeTree = self.asInstanceOf[WildcardTypeTree]
extension (self: pub.CaseDef) private[internal] inline def cast: CaseDef = self.asInstanceOf[CaseDef]
extension (self: pub.TypeCaseDef) private[internal] inline def cast: TypeCaseDef = self.asInstanceOf[TypeCaseDef]
extension (self: pub.Bind) private[internal] inline def cast: Bind = self.asInstanceOf[Bind]
extension (self: pub.Unapply) private[internal] inline def cast: Unapply = self.asInstanceOf[Unapply]
extension (self: pub.Alternatives) private[internal] inline def cast: Alternatives = self.asInstanceOf[Alternatives]
