package dotty.tools.sbtplugin

import com.typesafe.tools.mima.core._

object MiMaFilters {

  object Scala3Library {

    val ForwardsBreakingChanges: Map[String, Seq[ProblemFilter]] = Map(
      // Additions that require a new minor version of the library
      Versions.mimaPreviousDottyVersion -> Seq(
        // new feature: CanEqual support for NamedTuple
        ProblemFilters.exclude[DirectMissingMethodProblem]("scala.NamedTuple.namedTupleCanEqual"),
        // IArray integration with Scala Collections:
        ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.BuildFrom.buildFromIArray"),
        // IArray integration with Scala Collections:
        ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.generic.IsSeq.iarrayIsSeq"),
        // new annotation encoding capture checking's `x.except[C]` capabilities
        ProblemFilters.exclude[MissingClassProblem]("scala.annotation.internal.exceptCapability"),
    ))

    val BackwardsBreakingChanges: Map[String, Seq[ProblemFilter]] = Map(
      // In general we should never have backwards incompatible changes in the library.
      // Only exceptional cases should be added here.

      // Breaking changes since last reference version
      Versions.mimaPreviousDottyVersion -> Seq(

        // New @experimental capture-checking reflection API.
        // Quotes is only implemented by the compiler (QuotesImpl), which is
        // versioned together with the library, so adding abstract members is safe.
        ProblemFilters.exclude[ReversedMissingMethodProblem]("scala.quoted.Quotes#reflectModule.CapturingType"),
        ProblemFilters.exclude[ReversedMissingMethodProblem]("scala.quoted.Quotes#reflectModule.ReadOnlyCapability"),
        ProblemFilters.exclude[ReversedMissingMethodProblem]("scala.quoted.Quotes#reflectModule.OnlyCapability"),
        ProblemFilters.exclude[ReversedMissingMethodProblem]("scala.quoted.Quotes#reflectModule.ExceptCapability"),
        ProblemFilters.exclude[ReversedMissingMethodProblem]("scala.quoted.Quotes#reflectModule.RetainingAnnotation"),

        // scala/scala3#26100
        ProblemFilters.exclude[MissingTypesProblem]("scala.collection.immutable.LazyList"),
        ProblemFilters.exclude[MissingTypesProblem]("scala.collection.immutable.LazyList$MidEvaluation$"),
        ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.LazyList.<clinit>"),
        ProblemFilters.exclude[MissingTypesProblem]("scala.collection.immutable.LazyListIterable"),
        ProblemFilters.exclude[MissingClassProblem]("scala.collection.immutable.LazyListIterable$MidEvaluation$"),
        ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.LazyListIterable.<clinit>"),

        // Removal of unnecessary nested module fields that were always `null` (PR #25538)
        ProblemFilters.exclude[MissingFieldProblem]("scala.Array.UnapplySeqWrapper"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.CanEqual.derived"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.IArray#package.IArray"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.PartialFunction.ElementWiseExtractor"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.Predef.ArrowAssoc"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.Predef.Ensuring"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.Predef.StringFormat"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.Predef.any2stringadd"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.Tuple#package.EmptyTuple"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.experimental"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.deprecated"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.noAutoTupling"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.strictEquality"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.adhocExtensions"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.unsafeNulls"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.future"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.future-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.2.13"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.0-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.0"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.1-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.2-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.3-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.3"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.4-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.4"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.5-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.5"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.6-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.6"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.7-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.7"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.8-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.8"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.9-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.9"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.10-migration"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language.3.10"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#deprecated.symbolLiterals"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.namedTypeArguments"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.genericNumberLiterals"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.erasedDefinitions"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.strictEqualityPatternMatching"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.fewerBraces"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.saferExceptions"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.clauseInterleaving"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.pureFunctions"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.captureChecking"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.separationChecking"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.into"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.namedTuples"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.modularity"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.relaxedExtensionImports"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.betterMatchTypeExtractors"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.quotedPatternsWithPolymorphicFunctions"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.betterFors"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.packageObjectValues"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.multiSpreads"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.subCases"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.relaxedLambdaSyntax"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.language#experimental.safe"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.languageFeature.dynamics"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.languageFeature.postfixOps"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.languageFeature.reflectiveCalls"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.languageFeature.implicitConversions"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.languageFeature.higherKinds"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.languageFeature.existentials"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.languageFeature.experimental"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.languageFeature#experimental.macros"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.package.#::"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.IterableOps.SizeCompareOps"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.Searching.Found"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.Searching.InsertionPoint"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.Searching.SearchImpl"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.SeqFactory.UnapplySeqWrapper"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.StepperShape.Shape"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.View.Empty"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.View.Filter"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.package.+:"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.package.:+"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.concurrent.TrieMap.RemovalPolicy"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.convert.StreamExtensions.StreamShape"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.convert.StreamExtensions.StreamUnboxer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.convert.StreamExtensions.AccumulatorFactoryInfo"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.IntMap.Nil"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.IntMap.Tip"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.IntMap.Bin"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.LazyList.cons"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.LazyList.Deferrer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.LazyList.#::"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.LazyListIterable.cons"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.LazyListIterable.Deferrer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.LazyListIterable.#::"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.LongMap.Nil"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.LongMap.Tip"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.LongMap.Bin"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.Stream.cons"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.Stream.Empty"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.Stream.Deferrer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.Stream.#::"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.TreeSeqMap.OrderBy"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.TreeSeqMap.Ordering"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.TreeSeqMap#OrderBy.Insertion"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.TreeSeqMap#OrderBy.Modification"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.VectorMap.Tombstone"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.immutable.WrappedString.UnwrapOp"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.collection.mutable.UnrolledBuffer.Unrolled"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.compiletime.testing.ErrorKind.Parser"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.compiletime.testing.ErrorKind.Typer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.ExecutionContext.parasitic"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.ExecutionContext.Implicits"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.Future.never"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.Deadline.DeadlineIsOrdered"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.Duration.DurationIsOrdered"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.DurationConversions.spanConvert"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.DurationConversions.fromNowConvert"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.FiniteDuration.FiniteDurationIsOrdered"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.package.span"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.package.fromNow"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.package.DurationInt"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.package.DurationLong"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.package.DurationDouble"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.package.IntMult"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.package.LongMult"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.concurrent.duration.package.DoubleMult"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.DurationConverters.JavaDurationOps"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.DurationConverters.ScalaDurationOps"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaBiConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichBiConsumerAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaBiConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsBiConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichBiFunctionAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaBiPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichBiPredicateAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaBiPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsBiPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichBinaryOperatorAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaBooleanSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichBooleanSupplierAsFunction0"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaBooleanSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction0AsBooleanSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichConsumerAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaDoubleBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichDoubleBinaryOperatorAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaDoubleBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsDoubleBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaDoubleConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichDoubleConsumerAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaDoubleConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsDoubleConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichDoubleFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaDoublePredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichDoublePredicateAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaDoublePredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsDoublePredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaDoubleSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichDoubleSupplierAsFunction0"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaDoubleSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction0AsDoubleSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaDoubleToIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichDoubleToIntFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaDoubleToIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsDoubleToIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaDoubleToLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichDoubleToLongFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaDoubleToLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsDoubleToLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaDoubleUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichDoubleUnaryOperatorAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaDoubleUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsDoubleUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaIntBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichIntBinaryOperatorAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaIntBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsIntBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaIntConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichIntConsumerAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaIntConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsIntConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichIntFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaIntPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichIntPredicateAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaIntPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsIntPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaIntSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichIntSupplierAsFunction0"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaIntSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction0AsIntSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaIntToDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichIntToDoubleFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaIntToDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsIntToDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaIntToLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichIntToLongFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaIntToLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsIntToLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaIntUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichIntUnaryOperatorAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaIntUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsIntUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaLongBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichLongBinaryOperatorAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaLongBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsLongBinaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaLongConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichLongConsumerAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaLongConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsLongConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichLongFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaLongPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichLongPredicateAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaLongPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsLongPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaLongSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichLongSupplierAsFunction0"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaLongSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction0AsLongSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaLongToDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichLongToDoubleFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaLongToDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsLongToDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaLongToIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichLongToIntFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaLongToIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsLongToIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaLongUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichLongUnaryOperatorAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaLongUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsLongUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaObjDoubleConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichObjDoubleConsumerAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaObjDoubleConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsObjDoubleConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaObjIntConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichObjIntConsumerAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaObjIntConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsObjIntConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaObjLongConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichObjLongConsumerAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaObjLongConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsObjLongConsumer"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichPredicateAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsPredicate"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichSupplierAsFunction0"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction0AsSupplier"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaToDoubleBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichToDoubleBiFunctionAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaToDoubleBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsToDoubleBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaToDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichToDoubleFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaToDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsToDoubleFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaToIntBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichToIntBiFunctionAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaToIntBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsToIntBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaToIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichToIntFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaToIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsToIntFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaToLongBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichToLongBiFunctionAsFunction2"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaToLongBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction2AsToLongBiFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaToLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichToLongFunctionAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaToLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsToLongFunction"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.FromJavaUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichUnaryOperatorAsFunction1"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.AsJavaUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FunctionWrappers.RichFunction1AsUnaryOperator"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FutureConverters.FutureOps"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.FutureConverters.CompletionStageOps"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.OptionConverters.RichOptional"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.OptionConverters.RichOption"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.OptionConverters.RichOptionalDouble"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.OptionConverters.RichOptionalInt"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.jdk.OptionConverters.RichOptionalLong"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.BigDecimal.RoundingMode"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Implicits"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Unit"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Boolean"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Byte"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Char"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Short"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Int"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Long"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Float"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.DeprecatedFloatEquiv"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Double"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.DeprecatedDoubleEquiv"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.BigInt"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.BigDecimal"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.String"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv.Symbol"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv#Double.StrictEquiv"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv#Double.IeeeEquiv"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv#Float.StrictEquiv"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Equiv#Float.IeeeEquiv"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Fractional.Implicits"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Integral.Implicits"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.Implicits"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.BigIntIsIntegral"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.IntIsIntegral"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.ShortIsIntegral"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.ByteIsIntegral"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.CharIsIntegral"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.LongIsIntegral"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.FloatIsFractional"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.DoubleIsFractional"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.BigDecimalIsFractional"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Numeric.BigDecimalAsIfIntegral"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Implicits"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Unit"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Boolean"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Byte"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Char"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Short"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Int"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Long"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Float"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.DeprecatedFloatOrdering"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Double"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.DeprecatedDoubleOrdering"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.BigInt"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.BigDecimal"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.String"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering.Symbol"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering#Double.TotalOrdering"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering#Double.IeeeOrdering"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering#Float.TotalOrdering"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.math.Ordering#Float.IeeeOrdering"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.FromExpr.NoneFromExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.FromExpr.StringContextFromExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.FromExpr.EmptyTupleFromExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.FromExpr.NilFromExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.ArrayOfBooleanToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.ArrayOfByteToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.ArrayOfShortToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.ArrayOfCharToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.ArrayOfIntToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.ArrayOfLongToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.ArrayOfFloatToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.ArrayOfDoubleToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.NilToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.NoneToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.EmptyTupleToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.BigIntToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.BigDecimalToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.quoted.ToExpr.StringContextToExpr"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.LazyVals.Evaluating"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.LazyVals.NullValue"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.LazyVals.Names"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.Tuple2Zipped.Ops"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.Tuple3Zipped.Ops"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#deprecated.symbolLiterals"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.namedTypeArguments"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.genericNumberLiterals"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.erasedDefinitions"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.strictEqualityPatternMatching"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.fewerBraces"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.saferExceptions"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.clauseInterleaving"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.pureFunctions"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.captureChecking"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.separationChecking"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.into"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.namedTuples"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.modularity"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.relaxedExtensionImports"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.betterMatchTypeExtractors"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.quotedPatternsWithPolymorphicFunctions"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.betterFors"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.packageObjectValues"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.multiSpreads"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.subCases"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.runtime.stdLibPatches.language#experimental.relaxedLambdaSyntax"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.sys.Prop.FileProp"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.sys.Prop.StringProp"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.sys.Prop.IntProp"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.sys.Prop.DoubleProp"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.sys.process.BasicIO.LazilyListed"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.sys.process.BasicIO.Streamed"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.sys.process.BasicIO.Uncloseable"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.CommandLineParser.FromString"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.CommandLineParser#FromString.given_FromString_String"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.CommandLineParser#FromString.given_FromString_Boolean"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.CommandLineParser#FromString.given_FromString_Byte"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.CommandLineParser#FromString.given_FromString_Short"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.CommandLineParser#FromString.given_FromString_Int"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.CommandLineParser#FromString.given_FromString_Long"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.CommandLineParser#FromString.given_FromString_Float"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.CommandLineParser#FromString.given_FromString_Double"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.Either.MergeableEither"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.Either.LeftProjection"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.Either.RightProjection"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.FromDigits.NumberTooLarge"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.FromDigits.NumberTooSmall"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.FromDigits.MalformedNumber"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.FromDigits.BigIntFromDigits"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.FromDigits.BigDecimalFromDigits"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.Using.Manager"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.Using.Releasable"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.Using#Releasable.AutoCloseableIsReleasable"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.boundary.Break"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.package.chaining"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.control.Exception.Catch"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.control.TailCalls.Call"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.control.TailCalls.Done"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.control.TailCalls.Cont"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.matching.Regex.Match"),
        ProblemFilters.exclude[MissingFieldProblem]("scala.util.matching.Regex.Groups"),
      )
    )
  }

  object ScalaLibrarySJS {
    val ForwardsBreakingChanges: Map[String, Seq[ProblemFilter]] = Map(
      // Additions that require a new minor version of the library
      Versions.mimaPreviousDottyVersion -> Seq(
        // No .class files generated in the artifacts, only `scala.scalajs.*` files might be present
        ProblemFilters.exclude[MissingClassProblem]("scala.*"),
      ),
    )

    val BackwardsBreakingChanges: Map[String, Seq[ProblemFilter]] = Map(
      // We should never break backwards compatibility
      Versions.mimaPreviousDottyVersion -> Seq.empty,
    )
  }

  object TastyCore {
    val ForwardsBreakingChanges: Map[String, Seq[ProblemFilter]] = Map(
      // Additions that require a new minor version of tasty core
      Versions.mimaPreviousDottyVersion -> Seq(
      )
    )

    val BackwardsBreakingChanges: Map[String, Seq[ProblemFilter]] = Map(
      Versions.mimaPreviousDottyVersion -> Seq(
        // Removal of unnecessary nested module fields that were always `null` (PR #25538)
        ProblemFilters.exclude[MissingFieldProblem]("dotty.tools.tasty.TastyBuffer.Addr"),
        ProblemFilters.exclude[MissingFieldProblem]("dotty.tools.tasty.TastyBuffer.NameRef"),
        ProblemFilters.exclude[MissingFieldProblem]("dotty.tools.tasty.TastyFormat.NameTags"),
      )
    )
  }

  object Interfaces {
    val ForwardsBreakingChanges: Map[String, Seq[ProblemFilter]] = Map(
      // Additions that require a new minor version of interfaces
      Versions.mimaPreviousDottyVersion -> Seq.empty,
    )

    val BackwardsBreakingChanges: Map[String, Seq[ProblemFilter]] = Map.empty
  }

}
