import scala.language.dynamics

object Foo extends Dynamic:
  def applyDynamicNamed(name: String)(args: (String, Int)): Foo.type = this

object Test:
  def test(): Foo.type =
    Foo.xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
      .xxx(a = 1)
