#! /usr/bin/env bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

SOURCE=$DIR/Gen.scala
CLASS=./Gen.class

if [ ! -e $CLASS ] || [ $SOURCE -nt $CLASS ]; then
  ./bin/scalac $DIR/Gen.scala
fi

./bin/scala Gen $@

