#!/usr/bin/env bash

set -x

DIR="$( cd "$( dirname "$0" )" && pwd )"

for file in tests/debug/*.scala; do
   ./bin/dotc $file || exit 1
   ./bin/dotr -d Test&
   $DIR/Gen $file > robot
   expect robot

   if [[ $? != 0 ]]; then
      echo "debug test failed for file $file"
      exit 1
   fi
done

