#!/usr/bin/env bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

echo "start debug test..."
for file in tests/debug/*.scala; do
   ./bin/scalac $file || exit 1
   ./bin/scala -d Test > /dev/null &
   $DIR/Gen $file > robot
   expect robot 2>&1 > /dev/null

   if [[ $? != 0 ]]; then
      echo "debug test failed for file $file"
      exit 1
   fi

   echo "$file -- success"
done

echo "debug test success!"

