package dotty.tools.scaladoc
package site


/**
 * Object for rendering yaml front-matter for preprocessed markdowns.
 */
object FrontMatterRenderer:
  def render(properties: Map[String, Object]): String =

    def renderProperties(newProps: Map[String, Object]): List[String] = newProps.collect {
      case (k: String, v: String) => s"$k: $v"
    }.toList

    val rows = renderProperties(properties) ++ renderProperties(properties("page").asInstanceOf[Map[String, Object]])

    rows.mkString("---\n", "\n", "\n---") + "\n\n<!-- THIS FILE HAS BEEN GENERATED BY SCALADOC PREPROCESSOR.\n" +
      "    The whole process of generation the docs can be found under this README: https://github.com/lampepfl/dotty/blob/master/docs/README.md\n" +
     s"    The source file can be found here ${properties.get("urls").flatMap(_.asInstanceOf[Map[String, Object]].get("editSource")).getOrElse("")}\n" +
      "    NOTE THAT ANY CHANGES TO THIS FILE WILL BE OVERRIDEN BY PREPROCESSOR.\n" +
      "-->\n\n"



