#!/bin/bash -e

baseDir=${WORKSPACE-`pwd`}
scriptsDir="$baseDir/scripts"
. $scriptsDir/common

git log --pretty=format:"%h - %an, %aD : %s" -n 10
update DarkDimius scala scala-scala dotty-library
sbt $sbtArgs update compile test
