#!/bin/bash -e

baseDir=${WORKSPACE-`pwd`}
scriptsDir="$baseDir/scripts"
. $scriptsDir/common

git log --pretty=format:"%h - %an, %aD : %s" -n 10

sbt $sbtArgs update compile "partest-only run --show-diff --verbose"

