#!/bin/bash -e

baseDir=${WORKSPACE-`pwd`}
mkdir -p $baseDir/tests/partest-generated
touch $baseDir/tests/partest-generated/gen.log
exit 0
scriptsDir="$baseDir/scripts"
. $scriptsDir/common

git log --pretty=format:"%h - %an, %aD : %s" -n 10

update DarkDimius scala scala-scala dotty-library
sbt $sbtArgs update compile "partest-only --show-diff --verbose"

