name: MiMa Binary Compatibility Checks

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_call:

permissions:
  contents: read

env:
  DOTTY_CI_RUN: true

jobs:

  mima-scala-library-nonbootstrapped:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Git Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'

      - uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
      - name: Report MiMa issues in `scala-library-nonbootstrapped`
        run: ./project/scripts/sbt scala-library-nonbootstrapped/mimaReportBinaryIssues

  mima-scala3-interfaces:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.body, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'

      - uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
      - name: Report MiMa issues in `scala3-interfaces`
        run: ./project/scripts/sbt scala3-interfaces/mimaReportBinaryIssues

  mima-tasty-core-nonbootstrapped:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.body, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'

      - uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
      - name: Report MiMa issues in `tasty-core-nonbootstrapped`
        run: ./project/scripts/sbt tasty-core-nonbootstrapped/mimaReportBinaryIssues

  static-analysis-scala-library-bootstrapped:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.body, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'

      - uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
      - name: Report MiMa issues in `scala-library-bootstrapped`
        run: ./project/scripts/sbt scala-library-bootstrapped/mimaReportBinaryIssues

      - name: Report missingLink checks
        run: ./project/scripts/sbt scala-library-bootstrapped/missinglinkCheck

  mima-tasty-core-bootstrapped:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.body, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'

      - uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
      - name: Report MiMa issues in `tasty-core-bootstrapped`
        run: ./project/scripts/sbt tasty-core-bootstrapped/mimaReportBinaryIssues

  mima-scala-library-sjs:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.body, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'

      - uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
      - name: Report MiMa issues in `scala-library-sjs`
        run: ./project/scripts/sbt scala-library-sjs/mimaReportBinaryIssues
