###################################################################################################
###                  THIS IS A REUSABLE WORKFLOW TO PUBLISH SCALA TO CHOCOLATEY                 ###
### HOW TO USE:                                                                                 ###
###   - THE RELEASE WORKFLOW SHOULD CALL THIS WORKFLOW                                          ###
###   - IT WILL PUBLISH TO CHOCOLATEY THE MSI                                                   ###
###                                                                                             ###
### NOTE:                                                                                       ###
###   - WE SHOULD KEEP IN SYNC THE NAME OF THE MSI WITH THE ACTUAL BUILD                        ###
###   - WE SHOULD KEEP IN SYNC THE URL OF THE RELEASE                                           ###
###   - IT ASSUMES THAT THE `build-chocolatey` WORKFLOW WAS EXECUTED BEFORE                     ###
###################################################################################################


name: Publish Scala to Chocolatey
run-name: Publish Scala ${{ inputs.version }} to Chocolatey

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      # Connect to https://community.chocolatey.org/profiles/scala
      # Accessible via https://community.chocolatey.org/account
      API-KEY:
        required: true

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Fetch the Chocolatey package from GitHub
        uses: actions/download-artifact@v4
        with:
          name: scala.nupkg
      - name: Publish the package to Chocolatey
        run: choco push scala.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.API-KEY }}
        