name: Compile Full Standard Library

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:

  test-scala-library-nonbootstrapped:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.body, '[skip ci]')
    name: Non-Bootstrapped Library Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'
      - uses: sbt/setup-sbt@ce95da69b39609ea153bad087708da5f37366897 # v1.5.10
      - run: ./project/scripts/sbt scala-library-nonbootstrapped/test

  test-scala-library-bootstrapped:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.body, '[skip ci]')
    name: Bootstrapped Library Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'
      - uses: sbt/setup-sbt@ce95da69b39609ea153bad087708da5f37366897 # v1.5.10
      - run: ./project/scripts/sbt scala-library-bootstrapped/test

  scala-library-docs:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.body, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'

      - uses: sbt/setup-sbt@ce95da69b39609ea153bad087708da5f37366897 # v1.5.10
      - name: Generate Documentation of the Standard Library
        run: ./project/scripts/sbt scala-library-bootstrapped/doc
