name: Scala 3 with Capture Checking

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/test-cc.yml
      - scala2-library-cc/**
      - scala2-library-cc-tasty/**
      - compiler/src/dotty/tools/dotc/cc/**
      ## Capture Checking Tests
      - tests/pos-custom-args/captures/**
      - tests/run-custom-args/captures/**
      - tests/neg-custom-args/captures/**

env:
  DOTTY_CI_RUN: true
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  suite-with-stdlib-cc:
    name: Test Suite with the CC Standard Library
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - name: Test with Scala 2 library with CC TASTy
        run: ./project/scripts/sbt ";set ThisBuild/Build.scala2Library := Build.Scala2LibraryCCTasty ;scala3-bootstrapped/test"
