###################################################################################################
###                  THIS IS A REUSABLE WORKFLOW TO TEST SCALA WITH CHOCOLATEY                  ###
### HOW TO USE:                                                                                 ###
###                                                                                             ###
### NOTE:                                                                                       ###
###                                                                                             ###
###################################################################################################

name: Test 'scala' Chocolatey Package
run-name: Test 'scala' (${{ inputs.version }}) Chocolatey Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      java-version:
        required: true
        type    : string

env:
  CHOCOLATEY-REPOSITORY: chocolatey-pkgs
  DOTTY_CI_INSTALLATION: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
      - name: Download the 'nupkg' from GitHub Artifacts
        uses: actions/download-artifact@v4
        with:
          name: scala.nupkg
          path: ${{ env.CHOCOLATEY-REPOSITORY }}
      - name : Install the `scala` package with Chocolatey
        run  : choco install scala --source "${{ env.CHOCOLATEY-REPOSITORY }}" --pre # --pre since we might be testing non-stable releases
        shell: pwsh
      - name : Test the `scala` command
        run  : scala --version
        shell: pwsh
      - name : Test the `scalac` command
        run  : scalac --version
      - name : Test the `scaladoc` command
        run  : scaladoc --version
      - name : Uninstall the `scala` package
        run  : choco uninstall scala
        