 /* ref _empty_ */ object  /* ref java.lang.Object#`<init>`(). */ Enums /* <<< Enums. */  {
   /* ref scala.package.Serializable# */  /* ref scala. */  /* ref _root_ */  /* ref Enums. */ enum  /* ref java.lang.Object#`<init>`(). */ Colour /* <<< Enums.Colour# */  {
     /* ref java.lang.Object#`<init>`(). */  /* ref scala.package.Serializable# */  /* ref scala. */  /* ref _root_ */ case  /* ref scala.collection.IterableOnceOps#toArray(). */  /* ref scala.runtime.EnumValues#values(). */  /* ref Enums.Colour.$values. */  /* ref scala.reflect.ClassTag.apply(). */  /* ref scala.reflect.ClassTag. */  /* ref scala.runtime.EnumValues#`<init>`(). */  /* ref scala.collection.MapOps#apply(). */  /* ref scala.runtime.EnumValues#fromName(). */  /* ref Enums.Colour.valueOf().($name) */  /* ref java.util.NoSuchElementException# */  /* ref `<special-ops>`.throw(). */  /* ref java.lang.IllegalArgumentException#`<init>`(+2). */  /* ref java.lang.String#concat(). */  /* ref Enums.Colour#`<init>`(). */  /* ref Enums.Colour.$new().(_$ordinal) */  /* ref Enums.Colour.$new().($name) */  /* ref scala.runtime.EnumValues#register(). */  /* ref local0 */  /* ref local1 */ Red /* ref Enums.Colour.Red. */  /* <<< Enums.Colour.Red. */ , Gr /* <<< Enums.Colour.$values. */ een /* ref Enums.Colour.Green. */  /* <<< Enums.Colour.Green. */ , Blue /* ref Enums.Colour.Blue. */  /* <<< Enums.Colour.Blue. */
  }

  enum  /* ref java.lang.Object#`<init>`(). */ WeekDays /* <<< Enums.WeekDays# */  {
     /* ref Enums.WeekDays.Monday. */  /* ref Enums.WeekDays.Tuesday. */  /* ref Enums.WeekDays.Wednesday. */  /* ref Enums.WeekDays.Thursday. */  /* ref Enums.WeekDays.Friday. */  /* ref Enums.WeekDays.Saturday. */  /* ref Enums.WeekDays.Sunday. */  /* ref java.lang.Object#`<init>`(). */  /* ref scala.package.Serializable# */  /* ref scala. */  /* ref _root_ */  /* ref scala.collection.IterableOnceOps#toArray(). */  /* ref scala.runtime.EnumValues#values(). */  /* ref Enums.WeekDays.$values. */  /* ref scala.reflect.ClassTag.apply(). */  /* ref scala.reflect.ClassTag. */  /* ref scala.runtime.EnumValues#`<init>`(). */  /* ref scala.collection.MapOps#apply(). */  /* ref scala.runtime.EnumValues#fromName(). */  /* ref Enums.WeekDays.valueOf().($name) */  /* ref java.util.NoSuchElementException# */  /* ref `<special-ops>`.throw(). */  /* ref java.lang.IllegalArgumentException#`<init>`(+2). */  /* ref java.lang.String#concat(). */  /* ref Enums.WeekDays#`<init>`(). */  /* ref Enums.WeekDays.$new().(_$ordinal) */  /* ref Enums.WeekDays.$new().($name) */  /* ref scala.runtime.EnumValues#register(). */  /* ref local2 */  /* ref local3 */ case Monday /* <<< Enums.WeekDays.Monday. */
 /* <<< Enums.WeekDays.$values. */     case Tuesday /* <<< Enums.WeekDays.Tuesday. */
    case Wednesday /* <<< Enums.WeekDays.Wednesday. */
    case Thursday /* <<< Enums.WeekDays.Thursday. */
    case Friday /* <<< Enums.WeekDays.Friday. */
    case Saturday /* <<< Enums.WeekDays.Saturday. */
    case Sunday /* <<< Enums.WeekDays.Sunday. */
  }

  enum  /* ref java.lang.Object#`<init>`(). */ Maybe /* <<< Enums.Maybe# */ [+A] { /* <<< Enums.Maybe#`<init>`(). */  /* <<< Enums.Maybe#`<init>`().(A) */  /* <<< Enums.Maybe#(A) */  /* ref Enums.Maybe.None. */
     /* ref java.lang.Object#`<init>`(). */  /* ref scala.package.Serializable# */  /* ref scala. */  /* ref _root_ */  /* ref Enums.Maybe#`<init>`(). */  /* ref Enums.Maybe.Just#(A) */  /* ref Enums.Maybe.Just#`<init>`(). */  /* ref Enums.Maybe.Just#copy().(A) */  /* ref Enums.Maybe.Just#copy().(value) */  /* ref Enums.Maybe.Just.apply().(A) */  /* ref Enums.Maybe.Just.apply().(value) */  /* ref Enums.Maybe.Just.unapply().(A) */ case Just /* <<< Enums.Maybe.Just# */ (value /* <<< Enums.Maybe.Just#`<init>`(). */  /* <<< Enums.Maybe.Just#`<init>`().(value) */  /* <<< Enums.Maybe.Just#(value) */  /* <<< Enums.Maybe.Just#copy().(value) */  /* <<< Enums.Maybe.Just.apply().(value) */ : A /* ref Enums.Maybe.Just#`<init>`().(A) */  /* ref Enums.Maybe.Just#(value) */ ) /* ref scala.Product# */  /* ref scala. */  /* ref _root_ */  /* ref scala.package.Serializable# */
     /* ref Enums.Maybe#`<init>`(). */ case  /* <<< local4 */ None /* <<< Enums.Maybe.None. */  /* ref local5 */  /* ref local4 */
  }

  enum  /* ref java.lang.Object#`<init>`(). */ Tag /* <<< Enums.Tag# */ [A] {
 /* <<< Enums.Tag#`<init>`(). */  /* <<< Enums.Tag#`<init>`().(A) */  /* <<< Enums.Tag#(A) */  /* ref Enums.Tag.IntTag. */  /* ref Enums.Tag.BooleanTag. */      /* ref java.lang.Object#`<init>`(). */  /* ref scala.package.Serializable# */  /* ref scala. */  /* ref _root_ */ case IntTag /* <<< Enums.Tag.IntTag. */  extends Tag /* ref Enums.Tag# */ [I /* <<< local6 */ nt /* ref scala.Int# */ ] /* ref Enums.Tag#`<init>`(). */  /* ref local7 */  /* ref local6 */
    case BooleanTag /* <<< Enums.Tag.BooleanTag. */  extends Tag /* ref Enums.Tag# */ [B /* <<< local8 */ oolean /* ref scala.Boolean# */ ] /* ref Enums.Tag#`<init>`(). */  /* ref local9 */  /* ref local8 */
  }

  enum  /* ref java.lang.Object#`<init>`(). */ =:= /* <<< Enums.`=:=`# */ [A, B] /* <<< Enums.`=:=`#`<init>`(). */  /* <<< Enums.`=:=`#`<init>`().(A) */  /* <<< Enums.`=:=`#(A) */  /* <<< Enums.`=:=`#`<init>`().(B) */  /* <<< Enums.`=:=`#(B) */  {
     /* ref java.lang.Object#`<init>`(). */  /* ref scala.package.Serializable# */  /* ref scala. */  /* ref _root_ */  /* ref Enums.`=:=`.Refl#`<init>`(). */  /* ref Enums.`=:=`.Refl#copy().(C) */  /* ref Enums.`=:=`.Refl.apply().(C) */  /* ref Enums.`=:=`.Refl.unapply().(C) */ case Refl /* <<< Enums.`=:=`.Refl# */ [C]()  /* <<< Enums.`=:=`.Refl#`<init>`(). */  /* <<< Enums.`=:=`.Refl#`<init>`().(C) */  /* <<< Enums.`=:=`.Refl#(C) */  /* <<< Enums.`=:=`.Refl#copy().(C) */  /* <<< Enums.`=:=`.Refl.apply().(C) */  /* <<< Enums.`=:=`.Refl.unapply().(C) */ extends (C /* ref Enums.`=:=`.Refl#(C) */  /* ref Enums.`=:=`.Refl.apply().(C) */  =:= /* ref Enums.`=:=`# */  C /* ref Enums.`=:=`.Refl#(C) */  /* ref Enums.`=:=`.Refl.apply().(C) */  /* ref Enums.`=:=`#`<init>`(). */ ) /* ref scala.Product# */  /* ref scala. */  /* ref _root_ */  /* ref scala.package.Serializable# */
  }

  def unwrap /* <<< Enums.unwrap(). */ [A /* <<< Enums.unwrap().(A) */ ,B /* <<< Enums.unwrap().(B) */ ](opt /* <<< Enums.unwrap().(opt) */ : Option /* ref scala.Option# */ [A /* ref Enums.unwrap().(A) */ ])(given ev /* <<< Enums.unwrap().(ev) */ : A /* ref Enums.unwrap().(A) */  =:= /* ref Enums.`=:=`# */  Option /* ref scala.Option# */ [B /* ref Enums.unwrap().(B) */ ]): Option /* ref scala.Option# */ [B /* ref Enums.unwrap().(B) */ ] = {
    ev /* ref Enums.unwrap().(ev) */  match {
      case =:= /* ref Enums.`=:=`. */ .Refl /* ref Enums.`=:=`.Refl. */ () => opt /* ref Enums.unwrap().(opt) */ .flatMap /* ref scala.Option#flatMap(). */ (identity /* ref scala.Predef.identity(). */ [Option /* ref scala.Option# */ [B /* ref Enums.unwrap().(B) */ ]])
    }
  }

  enum Planet /* <<< Enums.Planet# */ (mass: /* <<< Enums.Planet#`<init>`(). */  /* <<< Enums.Planet#`<init>`().(mass) */  /* <<< Enums.Planet#(mass) */  Double /* ref scala.Double# */ , radius /* <<< Enums.Planet#`<init>`().(radius) */  /* <<< Enums.Planet#(radius) */ : Double /* ref scala.Double# */ ) extends java /* ref java. */ .lang /* ref java.lang. */ .Enum /* ref java.lang.Enum# */ [Planet /* ref Enums.Planet# */ ] /* ref java.lang.Enum#`<init>`(). */  /* ref Enums.Planet.Mercury. */  /* ref Enums.Planet.Venus. */  /* ref Enums.Planet.Earth. */  /* ref Enums.Planet.Mars. */  /* ref Enums.Planet.Jupiter. */  /* ref Enums.Planet.Saturn. */  /* ref Enums.Planet.Uranus. */  /* ref Enums.Planet.Neptune. */  {
    private final val G /* <<< Enums.Planet#G. */  = 6.67300E-11
    def surfaceGravity /* <<< Enums.Planet#surfaceGravity(). */  = G /* ref Enums.Planet#G. */  * /* ref scala.Double#`*`(+0). */  mass /* ref Enums.Planet#(mass) */  / /* ref scala.Double#`.`(+0). */  (radius /* ref Enums.Planet#(radius) */  * /* ref scala.Double#`*`(+0). */  radius /* ref Enums.Planet#(radius) */ )
    def surfaceWeight /* <<< Enums.Planet#surfaceWeight(). */ (otherMass /* <<< Enums.Planet#surfaceWeight().(otherMass) */ : Double /* ref scala.Double# */ ) = otherMass /* ref Enums.Planet#surfaceWeight().(otherMass) */  * /* ref scala.Double#`*`(+0). */  surfaceGravity /* ref Enums.Planet#surfaceGravity(). */

     /* ref java.lang.Object#`<init>`(). */  /* ref scala.package.Serializable# */  /* ref scala. */  /* ref _root_ */ case Mercury /* <<< Enums.Planet.$values. */  /* <<< Enums.Planet.Mercury. */  extends  /* ref scala.collection.IterableOnceOps#toArray(). */  /* ref scala.runtime.EnumValues#values(). */  /* ref Enums.Planet.$values. */  /* ref scala.reflect.ClassTag.apply(). */  /* ref scala.reflect.ClassTag. */  /* ref scala.runtime.EnumValues#`<init>`(). */  /* ref scala.collection.MapOps#apply(). */  /* ref scala.runtime.EnumValues#fromName(). */  /* ref Enums.Planet.valueOf().($name) */  /* ref java.util.NoSuchElementException# */  /* ref `<special-ops>`.throw(). */  /* ref java.lang.IllegalArgumentException#`<init>`(+2). */  /* ref java.lang.String#concat(). */ Plane /* <<< local10 */ t /* ref Enums.Planet# */  /* ref Enums.Planet#`<init>`(). */ (3.303e+23, 2.4397e6) /* ref scala.runtime.EnumValues#register(). */  /* ref Enums.Planet.$values. */  /* ref local11 */  /* ref local10 */
    case Venus /* <<< Enums.Planet.Venus. */    extends Plane /* <<< local12 */ t /* ref Enums.Planet# */  /* ref Enums.Planet#`<init>`(). */ (4.869e+24, 6.0518e6) /* ref scala.runtime.EnumValues#register(). */  /* ref Enums.Planet.$values. */  /* ref local13 */  /* ref local12 */
    case Earth /* <<< Enums.Planet.Earth. */    extends Plane /* <<< local14 */ t /* ref Enums.Planet# */  /* ref Enums.Planet#`<init>`(). */ (5.976e+24, 6.37814e6) /* ref scala.runtime.EnumValues#register(). */  /* ref Enums.Planet.$values. */  /* ref local15 */  /* ref local14 */
    case Mars /* <<< Enums.Planet.Mars. */     extends Plane /* <<< local16 */ t /* ref Enums.Planet# */  /* ref Enums.Planet#`<init>`(). */ (6.421e+23, 3.3972e6) /* ref scala.runtime.EnumValues#register(). */  /* ref Enums.Planet.$values. */  /* ref local17 */  /* ref local16 */
    case Jupiter /* <<< Enums.Planet.Jupiter. */  extends Plane /* <<< local18 */ t /* ref Enums.Planet# */  /* ref Enums.Planet#`<init>`(). */ (1.9e+27,   7.1492e7) /* ref scala.runtime.EnumValues#register(). */  /* ref Enums.Planet.$values. */  /* ref local19 */  /* ref local18 */
    case Saturn /* <<< Enums.Planet.Saturn. */   extends Plane /* <<< local20 */ t /* ref Enums.Planet# */  /* ref Enums.Planet#`<init>`(). */ (5.688e+26, 6.0268e7) /* ref scala.runtime.EnumValues#register(). */  /* ref Enums.Planet.$values. */  /* ref local21 */  /* ref local20 */
    case Uranus /* <<< Enums.Planet.Uranus. */   extends Plane /* <<< local22 */ t /* ref Enums.Planet# */  /* ref Enums.Planet#`<init>`(). */ (8.686e+25, 2.5559e7) /* ref scala.runtime.EnumValues#register(). */  /* ref Enums.Planet.$values. */  /* ref local23 */  /* ref local22 */
    case Neptune /* <<< Enums.Planet.Neptune. */  extends Plane /* <<< local24 */ t /* ref Enums.Planet# */  /* ref Enums.Planet#`<init>`(). */ (1.024e+26, 2.4746e7) /* ref scala.runtime.EnumValues#register(). */  /* ref Enums.Planet.$values. */  /* ref local25 */  /* ref local24 */
  }
}
